name: Test xlsx

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
            #- macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v1
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-stable
    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-stable
    - uses: jiro4989/setup-nim-action@master
    - name: Install xlsx
      run: nimble install https://github.com/xflywind/xlsx -y
    - name: Test command
      run: nimble test


  test_version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - stable
    steps:
    - uses: actions/checkout@v1
    - uses: jiro4989/setup-nim-action@master
      with:
        nim-version: ${{ matrix.version }}
    - name: Install xlsx
      run: nimble install https://github.com/xflywind/xlsx -y
    - name: Test command
      run: nimble test
